# railway.toml - Simple Railway deployment
[build]
builder = "nixpacks"

[deploy]
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
startCommand = "node server.js"

[env]
NODE_ENV = "production"
