# railway.toml - ENTERPRISE LEVEL: 8GB RAM + 8 vCPUs
[build]
builder = "nixpacks"

[deploy]
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "on_failure" 
startCommand = "node server.js"

[env]
NODE_ENV = "production"
NODE_OPTIONS = "--max-old-space-size=6000 --max-semi-space-size=1024"
UV_THREADPOOL_SIZE = "16"
