# railway.toml - Optimized for Railway Hobby Plan: 8GB RAM + 8 vCPUs
[build]
builder = "nixpacks"

[deploy]
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "on_failure" 
startCommand = "node server.js"
numReplicas = 1

[env]
NODE_ENV = "production"
NODE_OPTIONS = "--max-old-space-size=6144 --max-semi-space-size=1024 --expose-gc"
UV_THREADPOOL_SIZE = "16"
PLAYWRIGHT_BROWSERS_PATH = "/root/.cache/ms-playwright"
